version: "3.8"

services:
  # Database - Mongo DB
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: helpdev
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
