version: "3"
services:
  api:
    image: acme-main-app
    environment:
      SERVER_URL: "http://host.docker.internal:4000"
      LANDING_URL: "http://host.docker.internal:3000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web-cli:
    image: acme-main-server-app
    networks:
      - backend
    command: sh
