version: "3"
services:
  api:
    image: acme-main-server-app
    environment:
      JWT_REFRESH_SECRET: "acme refresh jwt secret 8888"
      JWT_ACCESS_SECRET: "acme access jwt secret 8888"
      MONGO_URI: "mongodb://helpdev:123456@host.docker.internal:27017/"
    build: .
    networks:
      - backend
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web-cli:
    image: acme-main-server-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
